### ISSUE TITLE
未来会兼容 laravel 9.x.x 版本或兼容计划是什么

### ISSUE THREAD

**Issue by van-chin** [youyingxiang/laravel-plugin#3]
yxx/laravel-plugin[v1.0.0, ..., v1.0.1] require laravel/framework ~6.0|~7.0|~8.0 

![image](https://user-images.githubusercontent.com/61791214/151106664-09207f6c-1d89-41b9-ab17-b4472d3c76ee.png)

**Comment by youxingxiang** [comment]
@van-chin 是 laravel9 安装 laravel-plugin 出现的报错吗

**Comment by van-chin** [comment]
是的 laravel 9 dev:master (9.x-dev) 安装的

**Comment by youyingxiang** [comment]
@van-chin 
* 会支持 `laravel 9`
* 会优化服务注册的逻辑，解决性能问题
* 会发布一个 `laravel-plugin-ui` 让用户可以可视化安装卸载
* 会发布一个 `admin` 后台，建立 `laravel-plugin` 生态，类似 `fastadmin`
